### PR TITLE
ci: Setup codecov action

### LINKED ISSUE #70: Setup Codecov
It is convenient for visualizing test coverage on GitHub and VS Code, especially since we are writing the kind of code where code coverage helps improve reliability.

### PR DESCRIPTION
**Pull request by ciscorn**
Closes #70

### CODE REVIEW

**Comment by ciscorn** [comment]
@xeho91 I’m having trouble accessing secrets.CODECOV_TOKEN. Do you have any idea what might be causing this?

**Comment by xeho91** [comment]
I was about to push a change, but you figured out already. Secrets are not forwarded between reusable workflows. You have to forward them.

I wish there was better error handling related to this case on GitHub Actions 😞

**Comment by ciscorn** [comment]
@xeho91 Thank you!
Personally, I always find workflow_run sufficient for my use cases, so I rarely use reusable_workflow…

**Comment by xeho91** [comment]
Could your current issue:

```
error - 2024-12-30 13:55:19,804 -- Upload failed: {"message":"Repository not found"}
```

be related that Codecov is trying to access `codecov.yml` on the `main` branch, where it doesn't exist yet?

**Comment by ciscorn** [comment]
I'd been mistakenly setting my personal token to this organizaiton...

**Review by xeho91 — APPROVED** [review]

**Comment by ciscorn** [comment]
Resolved 😌

**Comment by ciscorn** [comment]
Test coverage is now visible in both GitHub and VS Code.

On GitHub with Chrome extension (https://chromewebstore.google.com/detail/codecov/gedikamndpbemklijjkncpnolildpbgo)
image

VS Code extension:
image

**Pull request merged**
