### PR TITLE
chore: Include @ciscorn in project authors & contributors

### PR DESCRIPTION
**Pull request by xeho91**

### CODE REVIEW

**Comment by ciscorn** [comment]
Since I’m now part of the project, I think it might be better to move (or remove) the Acknowledgement section mentioning me and the Storybook to the end of the README. Just a suggestion!

**Comment by xeho91** [comment]
> Since I’m now part of the project, I think it might be better to move (or remove) the Acknowledgement section mentioning me and the Storybook to the end of the README. Just a suggestion!

Good point. Will change it shortly.

**Comment by xeho91** [comment]
@ciscorn I wasn't sure whether you'd like your email to be displayed in the `package.json#contributors`. If you're okay with it, you can add it and merge this PR.

**Comment by ciscorn** [comment]
Thank you very much for this PR!
No problem at all—I’ve added my email address.

**Pull request merged**
